---
title: "People"
---

## Nojin Kwak (co-director)

Nojin Kwak (Ph.D., University of Wisconsin-Madison) is a professor in the Department of Communication at the University at Buffalo. In addition to his appointment in Communication Studies, he currently serves as vice provost for international education. Kwak’s research centers on the role of communication media in civic and political engagement and has published in peer-reviewed journals, including *Communication Research, Journal of Communication*, *Human Communication Research*, *Political Communication*, *Political Research Quarterly*, *New Media and Society*, and *Asian Journal of Communication*. His recent studies analyze the impact of internet and mobile communication technologies on community involvement, deliberative openness, and political participation. He has received numerous top paper awards at major conferences. Kwak is a co-editor of a book series, Perspectives on Contemporary Korea, published by the University of Michigan Press.

contact: [njkwak@buffalo.edu](njkwak@buffalo.edu)

## Yini Zhang (co-director)

Yini Zhang (Ph.D., University of Wisconsin-Madison) is an assistant professor in the Department of Communication at the University at Buffalo. She applies computational methods to the study of networked actors on social media, information flows across traditional and social media, and their implications for journalism and democracy. Her work has been published in journals such as *Journal of Communication*, *Journal of Computer-Mediated Communication*, and *New Media & Society*.

contact: [yzhang20@buffalo.edu](yzhang20@buffalo.edu)

## New Members
